os: linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install .

script:
  - curl -o test.mp4 https://raw.githubusercontent.com/williamfzc/stagesep2-sample/master/videos/demo.mp4
  - cd example
  - python cut.py
  - python classify.py
  - python cut_and_classify.py
